export const data = [
  {
    id: 1,
    title: "iPhone 9",
    caption: "An apple mobile which is nothing like apple",
    brand: "Apple",
    url: "https://cdn.dummyjson.com/product-images/1/3.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    caption:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    brand: "Apple",
    category: "smartphones",
    url: "https://cdn.dummyjson.com/product-images/2/1.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    caption: "Samsung's new variant which goes beyond Galaxy to the Universe",
    brand: "Samsung",
    category: "smartphones",
    url: "https://cdn.dummyjson.com/product-images/3/1.jpg",
  },
  {
    id: 3,
    title: "Eau De Perfume Spray",
    caption:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    brand: "Lord - Al-Rehab",
    category: "fragrances",
    thumbnail: "https://cdn.dummyjson.com/product-images/15/thumbnail.jpg",
    url: ["https://cdn.dummyjson.com/product-images/15/2.jpg"],
  },
  {
    id: 4,
    title: "OPPOF19",
    caption: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    url: "https://cdn.dummyjson.com/product-images/4/2.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    caption:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    url: "https://cdn.dummyjson.com/product-images/5/2.jpg",
  },
  {
    id: 6,
    title: "MacBook Pro",
    caption:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    url: "https://cdn.dummyjson.com/product-images/6/1.png",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    caption:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
    url: "https://cdn.dummyjson.com/product-images/7/1.jpg",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    caption:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    url: "https://cdn.dummyjson.com/product-images/8/1.jpg",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    caption:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    url: "https://cdn.dummyjson.com/product-images/9/1.jpg",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    caption:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    url: "https://cdn.dummyjson.com/product-images/10/1.jpg",
  },
  {
    id: 11,
    title: "Non-Alcoholic Concentrated Perfume Oil",
    caption:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    brand: "Al Munakh",
    category: "fragrances",
    url: "https://cdn.dummyjson.com/product-images/14/3.jpg",
  },
  {
    id: 12,
    title: "Brown Perfume",
    caption: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 15.66,
    rating: 4,
    stock: 52,
    brand: "Royal_Mirage",
    category: "fragrances",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    url: "https://cdn.dummyjson.com/product-images/12/1.jpg",
  },
  {
    id: 13,
    title: "Fog Scent Xpressio Perfume",
    caption:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    price: 13,
    discountPercentage: 8.14,
    rating: 4.59,
    stock: 61,
    brand: "Fog Scent Xpressio",
    category: "fragrances",
    thumbnail: "https://cdn.dummyjson.com/product-images/13/thumbnail.webp",
    url: "https://cdn.dummyjson.com/product-images/13/1.jpg",
  },
  //   {
  //     id: 14,
  //     title: "Non-Alcoholic Concentrated Perfume Oil",
  //     caption:
  //       "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
  //     price: 120,
  //     discountPercentage: 15.6,
  //     rating: 4.21,
  //     stock: 114,
  //     brand: "Al Munakh",
  //     category: "fragrances",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/14/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/14/1.jpg"],
  //   },
  //   {
  //     id: 15,
  //     title: "Eau De Perfume Spray",
  //     caption:
  //       "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
  //     price: 30,
  //     discountPercentage: 10.99,
  //     rating: 4.7,
  //     stock: 105,
  //     brand: "Lord - Al-Rehab",
  //     category: "fragrances",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/15/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/15/1.jpg"],
  //   },
  //   {
  //     id: 16,
  //     title: "Hyaluronic Acid Serum",
  //     caption:
  //       "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
  //     price: 19,
  //     discountPercentage: 13.31,
  //     rating: 4.83,
  //     stock: 110,
  //     brand: "L'Oreal Paris",
  //     category: "skincare",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/16/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/16/1.png"],
  //   },
  //   {
  //     id: 17,
  //     title: "Tree Oil 30ml",
  //     caption:
  //       "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
  //     price: 12,
  //     discountPercentage: 4.09,
  //     rating: 4.52,
  //     stock: 78,
  //     brand: "Hemani Tea",
  //     category: "skincare",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/17/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/17/1.jpg"],
  //   },
  //   {
  //     id: 18,
  //     title: "Oil Free Moisturizer 100ml",
  //     caption:
  //       "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
  //     price: 40,
  //     discountPercentage: 13.1,
  //     rating: 4.56,
  //     stock: 88,
  //     brand: "Dermive",
  //     category: "skincare",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/18/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/18/1.jpg"],
  //   },
  //   {
  //     id: 19,
  //     title: "Skin Beauty Serum.",
  //     caption:
  //       "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
  //     price: 46,
  //     discountPercentage: 10.68,
  //     rating: 4.42,
  //     stock: 54,
  //     brand: "ROREC White Rice",
  //     category: "skincare",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/19/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/19/1.jpg"],
  //   },
  //   {
  //     id: 20,
  //     title: "Freckle Treatment Cream- 15gm",
  //     caption:
  //       "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
  //     price: 70,
  //     discountPercentage: 16.99,
  //     rating: 4.06,
  //     stock: 140,
  //     brand: "Fair & Clear",
  //     category: "skincare",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/20/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/20/1.jpg"],
  //   },
  //   {
  //     id: 21,
  //     title: "- Daal Masoor 500 grams",
  //     caption: "Fine quality Branded Product Keep in a cool and dry place",
  //     price: 20,
  //     discountPercentage: 4.81,
  //     rating: 4.44,
  //     stock: 133,
  //     brand: "Saaf & Khaas",
  //     category: "groceries",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/21/thumbnail.png",
  //     url: ["https://cdn.dummyjson.com/product-images/21/1.png"],
  //   },
  //   {
  //     id: 22,
  //     title: "Elbow Macaroni - 400 gm",
  //     caption: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
  //     price: 14,
  //     discountPercentage: 15.58,
  //     rating: 4.57,
  //     stock: 146,
  //     brand: "Bake Parlor Big",
  //     category: "groceries",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/22/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/22/3.jpg"],
  //   },
  //   {
  //     id: 23,
  //     title: "Orange Essence Food Flavou",
  //     caption:
  //       "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
  //     price: 14,
  //     discountPercentage: 8.04,
  //     rating: 4.85,
  //     stock: 26,
  //     brand: "Baking Food Items",
  //     category: "groceries",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/23/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/23/1.jpg"],
  //   },
  //   {
  //     id: 24,
  //     title: "cereals muesli fruit nuts",
  //     caption:
  //       "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
  //     price: 46,
  //     discountPercentage: 16.8,
  //     rating: 4.94,
  //     stock: 113,
  //     brand: "fauji",
  //     category: "groceries",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/24/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/24/1.jpg"],
  //   },
  //   {
  //     id: 25,
  //     title: "Gulab Powder 50 Gram",
  //     caption: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
  //     price: 70,
  //     discountPercentage: 13.58,
  //     rating: 4.87,
  //     stock: 47,
  //     brand: "Dry Rose",
  //     category: "groceries",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/25/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/25/1.png"],
  //   },
  //   {
  //     id: 26,
  //     title: "Plant Hanger For Home",
  //     caption:
  //       "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
  //     price: 41,
  //     discountPercentage: 17.86,
  //     rating: 4.08,
  //     stock: 131,
  //     brand: "Boho Decor",
  //     category: "home-decoration",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/26/1.jpg"],
  //   },
  //   {
  //     id: 27,
  //     title: "Flying Wooden Bird",
  //     caption:
  //       "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
  //     price: 51,
  //     discountPercentage: 15.58,
  //     rating: 4.41,
  //     stock: 17,
  //     brand: "Flying Wooden",
  //     category: "home-decoration",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/27/thumbnail.webp",
  //     url: ["https://cdn.dummyjson.com/product-images/27/thumbnail.webp"],
  //   },
  //   {
  //     id: 28,
  //     title: "3D Embellishment Art Lamp",
  //     caption:
  //       "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
  //     price: 20,
  //     discountPercentage: 16.49,
  //     rating: 4.82,
  //     stock: 54,
  //     brand: "LED Lights",
  //     category: "home-decoration",
  //     thumbnail: "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
  //     url: ["https://cdn.dummyjson.com/product-images/28/1.jpg"],
  //   },
];
